# Generated by Django 3.2.12 on 2022-03-12 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_needitem_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='needitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='meal.item'),
        ),
        migrations.AddField(
            model_name='needitem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
