# Generated by Django 3.2.12 on 2022-03-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_auto_20220312_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='description',
        ),
        migrations.RemoveField(
            model_name='market',
            name='item',
        ),
        migrations.RemoveField(
            model_name='market',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meal.market'),
        ),
    ]
