# Generated by Django 3.2.12 on 2022-03-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20220311_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
