# Generated by Django 3.2.12 on 2022-03-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_education_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='profile',
        ),
    ]
