# Generated by Django 3.2.12 on 2022-03-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_university_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='start_date',
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced')], default='3', max_length=1, null=True),
        ),
    ]
